### ISSUE TITLE
Change Color and Add Title/Custom Text

### ISSUE THREAD

**Issue by larry77** [ThierryO/qrcode#10]
Hello,

This is not a bug at all, but a feature request.
Would it be possible (at the moment I cannot do it, but perhaps it is my mistake)

1) Select the color of the matrix (e.g. blue on white)
2) Add a title to your QR code?

Many thanks

**Comment by ThierryO** [comment]
You can set the colours with [`plot()`](https://thierryo.github.io/qrcode/reference/plot.qr_code.html) and [`generate_svg()`](https://thierryo.github.io/qrcode/reference/generate_svg.html).

I'm reluctant to add a title. Every user will have different requirements for that. The `qrcode` object is a logical matrix. Hence you can incorporate that in the figure of your liking.

**Comment by larry77** [comment]
Alight, thanks!
