### ISSUE TITLE
Embed logos in QI codes?

### ISSUE THREAD

**Issue by badgettrg** [ThierryO/qrcode#11]
Would be great to be able to insert logos with in the code

**Comment by badgettrg** [comment]
thanks much, downloaded new version from CRAN, got:
`code <- qr_logo(x = url, logo = "Logo.jpg")`
Error in qr_logo(x = url, logo = "Logo.jpg") : 
  could not find function "qr_logo"

`packageVersion("qrcode")`
[1] ‘0.2.0’

I get the same error with
`remotes::install_github("ThierryO/qrcode", force = TRUE)`

All of my other packages and rtools are uptodate.

thanks

**Comment by ThierryO** [comment]
It seems like I forgot to export the function. Please try `qrcode:::qr_logo(x = url, logo = "Logo.jpg")`. I'll export it in the next version.
