### ISSUE TITLE
Dependencies have changed to R (≥ 4.1.0)

### ISSUE THREAD

**Issue by michael-morabito** [ThierryO/qrcode#14]
The latest version of qr_logo.R implements the native pipe operator ("|>"), which was not implemented in R until R 4.1.0.  If the problem code is isolted to a few spots in the most recent Nov 17th release, then these should be eradicated to maintain backward compatibility with R (≥ 3.0.0).

The CRAN repository states that R (≥ 3.0.0) is required.

THANK YOU!

**Comment by ThierryO** [comment]
Thanks for spotting this. The next version will depend on R (>= 4.1.0).
