### ISSUE TITLE
Add examples of reading the generated QR codes

### ISSUE THREAD

**Issue by jeroen** [ThierryO/qrcode#16]
The latest version of opencv can detect and decode QR codes: https://docs.ropensci.org/opencv/reference/qrcode.html

We could use this for unit tests or user examples of reading the generated QR back into R.

**Comment by ThierryO** [comment]
That would certainly be an option. I've noticed that `opencv` suggests `qrcode`. Don't we risk to get a circular dependency when `qrcode` suggests on `opencv`?

**Comment by jeroen** [comment]
That only is a problem for hard dependencies, like "Imports". But "Suggests" is a soft dependency, so either package can be loaded without the other, so there is no problem.

**Comment by ThierryO** [comment]
I wrote a little test function. It works with ascii but fails with special characters.

```
  test_read_qr <- function(input) {
    requireNamespace("opencv")
    test_file <- tempfile("qrcode", fileext = ".png")
    png(test_file)
    plot(qr_code(input))
    dev.off()
    opencv::ocv_read(test_file) |>
      opencv::ocv_qr_detect() |>
      expect_equal(input)
    rm(test_file)
  }
test_read_qr("\u00E6")
x <- "fa\xE7ile"
Encoding(x) <- "latin1"
test_read_qr(x)
```

```
Error: opencv::ocv_qr_detect(opencv::ocv_read(test_file)) (`actual`) not equal to `input` (`expected`).

`actual`:   "\xe6"
`expected`: "æ"   
In addition: Warning messages:
1: In grepl("\n", x) : unable to translate '<e6>' to a wide string
2: In grepl("\n", x) : input string 1 is invalid

Error: opencv::ocv_qr_detect(opencv::ocv_read(test_file)) (`actual`) not equal to `input` (`expected`).

`actual`:   "fa\xe7ile"
`expected`: "façile"   
In addition: Warning messages:
1: In grepl("\n", x) : unable to translate 'fa<e7>ile' to a wide string
2: In grepl("\n", x) : input string 1 is invalid
```

**Comment by ThierryO** [comment]
Below are the problematic qr codes. They give the correct output on my phone.

façile
![qr code with content "façile"](https://github.com/ThierryO/qrcode/assets/446636/182b80aa-7cee-40e6-9298-cca0e6f6cb35)

æ
![qr code with content "æ"](https://github.com/ThierryO/qrcode/assets/446636/bcc17258-e6e6-4023-9556-d9818abfe479)

**Comment by jeroen** [comment]
Good catch. I think the best solution is if you update qrcode to always call `enc2uf8` on the `input` text. Most widely used qr encoders/decoders assume text is UTF-8 encoded from what I [read from here](https://stackoverflow.com/questions/9699657/is-utf-8-the-encoding-of-choice-for-qr-codes-with-non-ascii-chars-by-now).

**Comment by ThierryO** [comment]
Handling UTF-8 as UTF-8 is not as simple as just using `enc2utf8`. I'm on a tight schedule due to a CRAN error. I'll use `opencv` only to test ASCII text.
